<?php

return [
    'parser' => [
        'name'          => 'Blocklist.DE',
        'enabled'       => true,
        'sender_map'    => [
            '/autogenerated@blocklist.de/',
        ],
        'body_map'      => [
            //
        ],
        'aliases'       => [
            'irc-bot' => 'ircbot',
            'reg-bot' => 'ircbot',
            'bad-bot' => 'badbot',
            'apacheddos' => 'ddos',
        ],
    ],

    'feeds' => [
        'login-attack' => [
            'class'     => '?',
            'type'      => 'Abuse',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],

        'info' => [
            'class'     => '?',
            'type'      => 'Info',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],

        'harvesting' => [
            'class'     => '?',
            'type'      => 'Abuse',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],

        'hack-attack' => [
            'class'     => '?',
            'type'      => 'Abuse',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],

        'ircbot' => [
            'class'     => '?',
            'type'      => 'Abuse',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],

        'regbot' => [
            'class'     => '?',
            'type'      => 'Abuse',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],

        'badbot' => [
            'class'     => '?',
            'type'      => 'Abuse',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],

        'ddos' => [
            'class'     => '?',
            'type'      => 'Abuse',
            'enabled'   => true,
            'fields'    => [
                //
            ],
        ],
    ],
];
